window.CC = window.CC || {};

CC.products = [
  {
    id: "the-250",
    name: "The 250",
    category: "house",
    brand: "Cigar Concierge",
    tag: "Limited Edition",
    badge: "limited",
    format: "Churchill bundle of 10",
    wrapper: "Premium Habano",
    origin: "Dominican Republic",
    strength: "Medium",
    price: 160,
    unit: "bundle of 10",
    stock: "Limited — 1,000 produced",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/the-250-bundles.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/the-250-bundles.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/house-bands.jpg"],
    video: "https://cigar-concierge-seattle.netlify.app/assets/videos/the-250.mp4",
    tweet: "2053154598316384319",
    blurb: "Aged Dominican Churchills rolled to celebrate 250 years of the Republic. Smoke some now. Save some for the Fourth.",
    notes: "Cedar, toasted almond, light baking spice, a long clean finish. Built for long conversations and July evenings.",
    story: "A small limited edition of 1,000 cigars. Aged Dominican filler finished in a premium Habano wrapper and banded with the Capitol / 250 mark. Bundles of 10 ship when the bell rings."
  },
  {
    id: "blockbuster",
    name: "Blockbuster",
    category: "house",
    brand: "Cigar Concierge",
    tag: "House Favorite",
    badge: "limited",
    format: "Box of 10",
    wrapper: "Cigar Concierge private blend",
    origin: "Dominican Republic",
    strength: "Medium-Full",
    price: 185,
    unit: "box of 10",
    stock: "Almost gone",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/blockbuster-lit.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/blockbuster-lit.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/house-bands.jpg"],
    video: "https://cigar-concierge-seattle.netlify.app/assets/videos/blockbuster.mp4",
    tweet: "2066382862140817882",
    blurb: "By a considerable margin, the favorite house release. 100/100 smooth.",
    notes: "Silk draw, cocoa, roasted coffee, a little cream, zero harshness. The cigar you hand a friend when you want them to understand the house style.",
    story: "Life’s too short to smoke bullshit cigars. Blockbuster is the blend the Concierge keeps reaching for — and the one clients write back about."
  },
  {
    id: "dawgfather",
    name: "The Dawgfather",
    category: "house",
    brand: "Cigar Concierge",
    tag: "Husky Nation LE",
    badge: "limited",
    format: "Pigtail Toro · box of 10",
    wrapper: "Maduro",
    origin: "Dominican Republic",
    strength: "Medium-Full",
    price: 185,
    unit: "box of 10",
    stock: "In stock — very limited",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/dawgfather-box.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/dawgfather-box.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/dawgfather-lid.jpg"],
    video: "https://cigar-concierge-seattle.netlify.app/assets/videos/dawgfather.mp4",
    tweet: "2093038501113868373",
    blurb: "Highly aged Dominican filler and binder under a smooth, flavorful Maduro. Rolled pigtail toro for Husky nation.",
    notes: "Dark chocolate, espresso, leather, a sweet maduro edge. Built for night games and porch victories.",
    story: "Say who, say what. A purple-reign box for people who bleed Montlake. Limited production, allocated first to clients who already know the bell."
  },
  {
    id: "spacemob",
    name: "SpaceMob",
    category: "house",
    brand: "Cigar Concierge",
    tag: "Community Blend",
    badge: "limited",
    format: "Bundle of 10",
    wrapper: "Aged Dominican",
    origin: "Dominican Republic — house factory",
    strength: "Medium",
    price: 160,
    unit: "bundle of 10",
    stock: "Available",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/spacemob-band.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/spacemob-band.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/house-bands.jpg"],
    video: "https://cigar-concierge-seattle.netlify.app/assets/videos/summer-sneak.mp4",
    tweet: "2072143094821298378",
    blurb: "Aged Dominican cigars manufactured at the house factory. The only retail group with its own stick.",
    notes: "Earthy Dominican core, honeyed cedar, a slow evolving mid-smoke. Celebratory without being loud.",
    story: "Rolled for milestones — batch shipments, long nights on the thesis, and people who like their cigars with a private joke on the band."
  },
  {
    id: "pigtail-toro",
    name: "Pigtail Toro",
    category: "house",
    brand: "Cigar Concierge",
    tag: "House Blend",
    badge: "limited",
    format: "Pigtail Toro · bundle of 10",
    wrapper: "House selection",
    origin: "Dominican Republic",
    strength: "Medium",
    price: 160,
    unit: "bundle of 10",
    stock: "Low — about 10 bundles",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/house-bands.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/house-bands.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/blockbuster-lit.jpg"],
    video: "https://cigar-concierge-seattle.netlify.app/assets/videos/summer-sneak.mp4",
    tweet: "2052922041188454735",
    blurb: "A nuanced profile that evolves from first light to the nub. Utterly magnificent.",
    notes: "Opens sweet and floral, turns to toasted nuts and baking spice, finishes long and clean. Easy draw, serious construction.",
    story: "The everyday-special stick. Same factory, same obsession with aged Dominican leaf, finished in the signature pigtail cap."
  },
  {
    id: "opus-x-25",
    name: "Opus X 25th Anniversary",
    category: "vault",
    brand: "Arturo Fuente",
    tag: "Allocated Vault",
    badge: "vault",
    format: "Box",
    wrapper: "Dominican Rosado",
    origin: "Dominican Republic · Chateau de la Fuente",
    strength: "Full",
    price: null,
    unit: "box — inquire",
    stock: "Rare — when allocated",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/opus-x-25.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/opus-x-25.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/opus-lineup.jpg"],
    tweet: "2027241895093752009",
    blurb: "More of a transformational experience than a cigar. One of Carlito Fuente’s masterpieces.",
    notes: "Pepper, dark fruit, cedar, that unmistakable Opus sweetness. A special-occasion smoke that actually deserves the phrase.",
    story: "Nobody has rare cigars like Cigar Concierge. When a 25th Anniversary box lands, it does not sit. Request allocation."
  },
  {
    id: "opus-baby-shark",
    name: "Opus X Shark 77",
    category: "vault",
    brand: "Arturo Fuente",
    tag: "Allocated Vault",
    badge: "vault",
    format: "Box of 30",
    wrapper: "Dominican Rosado",
    origin: "Dominican Republic",
    strength: "Full",
    price: null,
    unit: "box of 30 — inquire",
    stock: "Allocated",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/opus-baby-shark.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/opus-baby-shark.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/opus-lineup.jpg"],
    blurb: "Baby Shark 77 Opus X. The red-felt box people screenshot.",
    notes: "Classic Fuente spice over a rich, oily wrapper. Shark vitola changes the burn and the drama.",
    story: "Vault piece. Boxes move through the concierge list — not a public shelf."
  },
  {
    id: "opus-phantom",
    name: "2009 Opus X Forbidden Phantom",
    category: "vault",
    brand: "Arturo Fuente",
    tag: "Aged Vault",
    badge: "vault",
    format: "Single coffin",
    wrapper: "Dominican Rosado",
    origin: "Dominican Republic",
    strength: "Full",
    price: null,
    unit: "single — inquire",
    stock: "Aged inventory",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/opus-phantom.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/opus-phantom.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/opus-lineup.jpg"],
    tweet: "2088470888232661073",
    blurb: "A 2009 Forbidden X Lancero in the original wooden coffin.",
    notes: "Time has rounded the pepper into cocoa, cedar, and a dry champagne finish. Serious collector smoke.",
    story: "Aged inventory is the concierge edge. This is what seventeen years in the right humidor does."
  },
  {
    id: "davidoff-100",
    name: "Davidoff 100th Diadema Fina",
    category: "vault",
    brand: "Davidoff",
    tag: "Aged Vault",
    badge: "vault",
    format: "Diadema Fina",
    wrapper: "Ecuadorian / Dominican",
    origin: "Dominican Republic",
    strength: "Medium",
    price: null,
    unit: "inquire",
    stock: "Ultra rare",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/davidoff-100.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/davidoff-100.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/davidoff-35.jpg"],
    tweet: "2091379854424015016",
    blurb: "Best Davidoff of all time. 2006 100th Anniversary Diadema Fina. Unreal.",
    notes: "Cream, white pepper, roasted nuts, a polished davidoff sweetness that only age unlocks.",
    story: "The box art alone is a museum piece. The cigar is why people stay on the list."
  },
  {
    id: "davidoff-35",
    name: "Davidoff 35th Anniversary LE",
    category: "vault",
    brand: "Davidoff",
    tag: "20-Year Aged",
    badge: "vault",
    format: "Limited Edition box",
    wrapper: "Aged Davidoff",
    origin: "Dominican Republic",
    strength: "Medium",
    price: null,
    unit: "box — inquire",
    stock: "A few boxes",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/davidoff-35.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/davidoff-35.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/davidoff-100.jpg"],
    tweet: "2027153071504265352",
    blurb: "20-year aged 2006 Limited Edition. Look at how yellow the bands are.",
    notes: "Honey, cedar, light leather, that aged-band aroma before you even cut it.",
    story: "Special edition for Old Virginia Tobacco Company. Yellowed bands, correct storage, no stories needed."
  },
  {
    id: "davidoff-rooster",
    name: "Davidoff Limited Edition Rooster",
    category: "vault",
    brand: "Davidoff",
    tag: "Limited Edition",
    badge: "vault",
    format: "Limited Edition",
    wrapper: "Dark Ecuadorian",
    origin: "Dominican Republic",
    strength: "Medium-Full",
    price: null,
    unit: "inquire",
    stock: "Allocated",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/davidoff-rooster.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/davidoff-rooster.jpg"],
    tweet: "2087386172406510077",
    blurb: "Davidoff Limited Edition Rooster. Life’s too short to smoke bullshit cigars.",
    notes: "Baking spice, cocoa, a little red fruit on a darker wrapper than the classic Davidoff profile.",
    story: "A holiday / year-of-the-rooster special that almost never hits a regular humidor."
  },
  {
    id: "padron-1964",
    name: "1999 Padrón 1964 Imperiales",
    category: "vault",
    brand: "Padrón",
    tag: "Aged Box",
    badge: "vault",
    format: "Box of 25",
    wrapper: "Nicaraguan Natural",
    origin: "Nicaragua",
    strength: "Full",
    price: null,
    unit: "box of 25 — inquire",
    stock: "Aged box available",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/padron-1964.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/padron-1964.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/padron-50.jpg"],
    tweet: "2050705156115988797",
    blurb: "A 1999 box of 1964 Anniversary Imperiales. That is not a typo.",
    notes: "Cocoa, roasted espresso, earth, a Padrón oil sheen. Age has made it velvety rather than sharp.",
    story: "Buying new 1964s is easy. Buying a box that has been quietly aging since 1999 is why the concierge exists."
  },
  {
    id: "padron-50",
    name: "Padrón 50th Natural",
    category: "vault",
    brand: "Padrón",
    tag: "Allocated",
    badge: "vault",
    format: "3-packs",
    wrapper: "Nicaraguan Natural",
    origin: "Nicaragua",
    strength: "Full",
    price: null,
    unit: "3-pack — inquire",
    stock: "3 packs available",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/padron-50.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/padron-50.jpg"],
    tweet: "2027026423836266726",
    blurb: "Padrón 50 Natural. Three packs on the list.",
    notes: "Classic anniversary-series density: chocolate, coffee, a little pepper on the retrohale.",
    story: "When the 50ths show up they do not linger. Request the pack."
  },
  {
    id: "opus-lineup",
    name: "Fuente Opus X Allocation",
    category: "vault",
    brand: "Arturo Fuente",
    tag: "Concierge Sourcing",
    badge: "vault",
    format: "By request",
    wrapper: "Varies",
    origin: "Dominican Republic",
    strength: "Full",
    price: null,
    unit: "inquire",
    stock: "Rotating",
    image: "https://cigar-concierge-seattle.netlify.app/assets/images/opus-lineup.jpg",
    gallery: ["https://cigar-concierge-seattle.netlify.app/assets/images/opus-lineup.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/opus-x-25.jpg", "https://cigar-concierge-seattle.netlify.app/assets/images/opus-baby-shark.jpg"],
    blurb: "Perfecxion, Belicoso XXX, Reserva d’Chateau, Forbidden, Amor del Destino — sourced as they surface.",
    notes: "Tell the concierge the vitola and the year. The list does the rest.",
    story: "The profile picture is the promise: the rare Fuente bench, in house, not in a catalog screenshot from 2014."
  }
];

CC.videos = [
  { title: "The Dawgfather is in stock", src: "https://cigar-concierge-seattle.netlify.app/assets/videos/dawgfather.mp4", tweet: "2093038501113868373", copy: "Maduro pigtail toro. Boxes of 10 — $185. Husky nation only." },
  { title: "Blockbuster — summer preorder", src: "https://cigar-concierge-seattle.netlify.app/assets/videos/blockbuster.mp4", tweet: "2066382862140817882", copy: "Boxes of 10 on preorder. $185. The house favorite." },
  { title: "The 250 being banded", src: "https://cigar-concierge-seattle.netlify.app/assets/videos/the-250.mp4", tweet: "2053154598316384319", copy: "1,000 produced. Aged Dominican Churchills for the country’s birthday." },
  { title: "Summer sneak peek", src: "https://cigar-concierge-seattle.netlify.app/assets/videos/summer-sneak.mp4", tweet: "2054596534646587681", copy: "A look at the warm-weather house cigar before it hit the list." }
];

CC.embeds = [
  { id: "2093038501113868373", title: "Dawgfather drop" },
  { id: "2066382862140817882", title: "Blockbuster preorder" },
  { id: "2053154598316384319", title: "The 250 — half presold" },
  { id: "2054596534646587681", title: "Summer sneak peek" },
  { id: "2078703927139438797", title: "Blockbuster, favorite release" },
  { id: "2074929499934978194", title: "SpaceMob aged Dominican" },
  { id: "2072143094821298378", title: "SpaceMob in production" },
  { id: "2052922041188454735", title: "Pigtail Toro bundles" }
];
